name: Update Calendar Events

# Déclenchement automatique tous les jours à 6h UTC, ou à la main
on:
  schedule:
    - cron: '0 6 * * 1'  # tous les lundis à 6h UTC
  workflow_dispatch:      # bouton manuel dans GitHub Actions

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false # a MUST HAVE

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer dependencies
        run: |
          pip install requests

      - name: Exécuter le script Python
        run: python scripts/add_events.py

      - name: Commit & push si modification
        run: |
          git config --global user.name "quentinlaval"
          git config --global user.email "quentin.laval@u-bordeaux.fr"
          git add data/events.json
          git commit -m "Mise à jour auto des événements" || echo "Aucun changement"
          git remote set-url origin "https://x-access-token:${{ secrets.WEB_BBPH }}@github.com/${{ github.repository }}"
          git push origin HEAD:main
